fullhouse/auth/backend/urls.py
"""
URLconf for registration and activation, using django-registration's
default backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.default.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize the behavior (e.g., by passing extra
arguments to the various views) or split up the URLs, feel free to set
up your own URL patterns for these views instead.

"""


from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from registration.views import activate
from registration.views import register

urlpatterns = patterns('',
    url(r'^activate/complete/$',
        direct_to_template,
        {'template': 'registration/activation_complete.html'},
        name='registration_activation_complete'),
    # Activation keys get matched by \w+ instead of the more specific
    # [a-fA-F0-9]{40} because a bad activation key should still get to the
    # view; that way it can return a sensible "invalid key" message instead
    # of a confusing 404.
    url(r'^activate/(?P<activation_key>\w+)/$',
        activate,
        {'backend': 'fullhouse.auth.backend.FullhouseBackend'},
        name='registration_activate'),
    url(r'^register/$',
        register,
        {'backend': 'fullhouse.auth.backend.FullhouseBackend'},
        name='registration_register'),
    url(r'^register/complete/$',
        direct_to_template,
        {'template': 'registration/registration_complete.html'},
        name='registration_complete'),
    url(r'^register/closed/$',
        direct_to_template,
        {'template': 'registration/registration_closed.html'},
        name='registration_disallowed'),
    url(r'', include('fullhouse.auth.auth_urls')),
)

fullhouse/auth/urls.py
"""
URLconf for registration and activation, using django-registration's
default backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.default.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize the behavior (e.g., by passing extra
arguments to the various views) or split up the URLs, feel free to set
up your own URL patterns for these views instead.

"""


from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from registration.views import activate
from fullhouse.auth.views import register

urlpatterns = patterns(
    '',
    url(r'^activate/complete/$',
        direct_to_template,
        {'template': 'registration/activation_complete.html'},
        name='registration_activation_complete'),
    # Activation keys get matched by \w+ instead of the more specific
    # [a-fA-F0-9]{40} because a bad activation key should still get to the
    # view; that way it can return a sensible "invalid key" message instead
    # of a confusing 404.
    url(r'^activate/(?P<activation_key>\w+)/$',
        activate,
        {'backend': 'fullhouse.auth.backend.FullhouseBackend'},
        name='registration_activate'),
    url(r'^register/$',
        register,
        {'backend': 'fullhouse.auth.backend.FullhouseBackend'},
        name='registration_register'),
    url(r'^register/complete/$',
        direct_to_template,
        {'template': 'registration/registration_complete.html'},
        name='registration_complete'),
    url(r'^register/closed/$',
        direct_to_template,
        {'template': 'registration/registration_closed.html'},
        name='registration_disallowed'),
    url(r'', include('fullhouse.auth.backend.auth_urls')),
)

fullhouse/dashboard/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template

import views

urlpatterns = patterns(
    '',
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^create_house/$',
        views.create_house,
        name='dashboard_create_house'),
    url(r'^add_members/$',
        views.add_members,
        name='dashboard_add_members'),
    url(r'^add_members/complete/$',
        direct_to_template,
        {'template': 'addmembers/add_members_complete.html'}),
    url(r'^join_house/(?P<invite_key>\w+)/$',
        views.join_house,
        name='dashboard_join_house'),
    url(r'^announcement/new/$',
        views.create_announcement,
        name='create_announcement'),
    url(r'^announcement/edit/$',
        views.edit_announcement,
        name='edit_announcement'),
    url(r'^task/new/$',
        views.create_task,
        name='create_task'),
    url(r'^task/edit/$',
        views.edit_task,
        name='edit_task'),
    url(r'^task/update/(?P<action>\w+)/$',
        views.update_task,
        name='update_task'),
    url(r'^task/history/$',
        views.task_history,
        name='task_history'),
    url(r'^user_settings/$',
        views.edit_user,
        name='edit_user'),
    url(r'^house_settings/$',
        views.edit_house,
        name='edit_house'),
)

fullhouse/urls.py
from django.conf.urls import patterns, include, url, handler404, handler403

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

from fullhouse.dashboard import views

urlpatterns = patterns(
    '',
    url(r'^$', views.home, name='home'),
    url(r'^welcome/$', views.welcome, name='welcome'),
    url(r'^about_us/$', views.about_us, name='about_us'),
    url(r'^dashboard/', include('fullhouse.dashboard.urls')),
    url(r'^accounts/', include('fullhouse.auth.urls')),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^contact_us/$', views.contact_us, name='contact_us'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

handler404 = 'fullhouse.dashboard.views.handler404'
handler403 = 'fullhouse.dashboard.views.handler403'

# for debug only! django is not made to serve static files in prod
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

fullhouse/dashboard/models.py
import datetime
import hashlib
import random
import pdb

from django.conf import settings
from django.core.mail import send_mail
from django.core.validators import *
from django.contrib.auth.models import User
from django.contrib.sites.models import RequestSite
from django.contrib.sites.models import Site

from django.db import models
from django.template.loader import render_to_string
from django.utils.translation import ugettext_lazy as _

try:
    from django.utils.timezone import now as datetime_now
except ImportError:
    datetime_now = datetime.datetime.now

from registration.models import SHA1_RE

import logging

logger = logging.getLogger(__name__)

# Notes:
# - Django automatically creates an 'id' field as a primary key
# - I've created alright __str__ methods, but feel free to change them to
#   suit you
# - Because we use the related_name argument when defining foreign keys, you
#   can access UserProfiles and Announcements through House objects.
#   For example:
#   h = House.objects.get(name='my house')
#   h.members.all()
#   This lists all of the members of the given house.


class House(models.Model):
    name = models.CharField(max_length=30)
    zip_code = models.CharField(max_length=9, validators=[RegexValidator(regex=r'^[0-9]{5}$', message="Please enter a 5 digit zip code.")], null=True, blank=True)

    def __str__(self):
        return self.name


class InviteManager(models.Manager):

    def is_valid(self, user, invite_key):
        """
        TODO: documentation
        """
        if SHA1_RE.search(invite_key):
            try:
                invite = self.get(invite_key=invite_key)
            except self.model.DoesNotExist:
                return False
            return not invite.invite_key_expired() and user.email == invite.email
        return False

    def accept_invite(self, user, invite_key):
        """
        TODO: documentation
        """
        if SHA1_RE.search(invite_key):
            try:
                invite = self.get(invite_key=invite_key)
            except self.model.DoesNotExist:
                return False
            if not invite.invite_key_expired() and user.email == invite.email:
                profile = user.profile
                profile.house = invite.house
                profile.save()
                invite.invite_key = self.model.INVITE_ACCEPTED
                invite.save()
                return user
        return False

    def create_member_invite(self, email, from_user, house):
        salt = hashlib.sha1(str(random.random())).hexdigest()[:5]
        housename = house.name
        if isinstance(email, unicode):
            housename = housename.encode('utf-8')
        if isinstance(email, unicode):
            email = email.encode('utf-8')

        invite_key = hashlib.sha1(salt + email + housename).hexdigest()
        invite_profile = self.create(
            house=house,
            email=email,
            invite_key=invite_key,
            sent_date=datetime_now()
        )

        if Site._meta.installed:
            site = Site.objects.get_current()
        else:
            site = RequestSite(request)
        invite_profile.send_invite_email(site, from_user)

        return invite_profile

    def delete_expired_invites(self):
        for profile in self.all():
            if profile.invite_key_expired():
                profile.delete()


class InviteProfile(models.Model):

    INVITE_ACCEPTED = u"ALREADY_ACCEPTED"

    house = models.ForeignKey(House, related_name='invitees')
    email = models.EmailField()
    invite_key = models.CharField(_('house invite key'), max_length=40)
    sent_date = models.DateTimeField()

    objects = InviteManager()

    def invite_key_expired(self):
        expiration_date = datetime.timedelta(
            days=settings.INVITE_ACTIVATION_DAYS
        )
        return self.invite_key == self.INVITE_ACCEPTED or \
            (self.sent_date + expiration_date <= datetime_now())

    def send_invite_email(self, site, from_user):
        members = [unicode(member) for member in self.house.members.all()]
        invitees = [x.email for x in self.house.invitees.all() if not x.invite_key_expired()]

        ctx_dict = {'invite_key': self.invite_key,
                    'expiration_days': settings.INVITE_ACTIVATION_DAYS,
                    'from_username': from_user.username,
                    'housename': self.house.name,
                    'site': site,
                    'members': members,
                    'invitees': invitees}
        subject = render_to_string('addmembers/invite_email_subject.txt',
                                   ctx_dict)
        subject = ''.join(subject.splitlines())
        message = render_to_string('addmembers/invite_email.txt',
                                   ctx_dict)

        if Site._meta.installed:
            site = Site.objects.get_current()
        else:
            site = RequestSite(request)
        from_email = settings.DEFAULT_FROM_EMAIL

        send_mail(subject, message, from_email, (self.email,))

    def __str__(self):
        return self.email


class UserProfile(models.Model):

    MALE = 'mm'
    FEMALE = 'ff'
    # There's a pc issue here, but
    # we allow the gender to be blank
    GENDER_CHOICES = (
        (MALE, 'male'),
        (FEMALE, 'female'),
    )

    user = models.OneToOneField(User, related_name='profile')
    birthday = models.DateField(null=True, blank=True)
    gender = models.CharField(
        max_length=4, choices=GENDER_CHOICES, null=True, blank=True
    )
    # should perhaps be a ManyToManyField, but for simplicity, we'll only allow
    # one house per person for now.
    house = models.ForeignKey(
        House, related_name='members', null=True, on_delete=models.SET_NULL
    )

    def __str__(self):
        if self.user.first_name or self.user.last_name:
            return self.user.first_name + " " + self.user.last_name + " <" + self.user.email + ">"
        else:
            return self.user.email


class Announcement(models.Model):
    creator = models.ForeignKey(UserProfile)
    text = models.TextField()
    house = models.ForeignKey(House, related_name='announcements')
    expiration = models.DateField(null=True)

    def __str__(self):
        return "%s: %s" % (self.creator, self.text)

    class Meta:
        ordering = ['-id']


class TaskManager(models.Manager):

    def create_task(self, creator, task_form):
        """
        Create a new ``Task`` and a ``TaskInstance`` due at the task's
        first_due date.

        `creator` - ``UserProfile`` of the task's creator

        `create_task_form` - bound and verified ``CreateTaskForm`` with data
            for new task

        """

        assert task_form.is_valid()

        task = task_form.save(commit=False)
        task.creator = creator
        task.house = creator.house
        task.is_active = True
        task.save()
        #need to save many to many data
        task_form.save_m2m()

        current = TaskInstance.objects.create(
            task=task,
            #random first assignee
            assignee=random.choice(task.participants.all()),
            due_date=task.first_due,
        )
        current.save()

    def update_taskinstance(self, t_id, userprofile, action):
        """
        Update TaskInstance with given id. No-op if the taskinstance
        does not exist, or if the user associated with given userprofile
        is not a participant in the task.
        Repeated calls to this function with the same parameters will
        not change models from their state after the first call.

        """

        try:
            instance = TaskInstance.objects.get(id=t_id)
        except TaskInstance.DoesNotExist:
            return
        if userprofile not in instance.task.participants.all():
            return
        if action == 'complete':
            if instance.completed_by is not None:
                return
            instance.complete(userprofile)
            instance.save()

            task = instance.task
            if task.frequency == Task.ONCE:
                task.is_active = False
                task.save()
            elif (task.is_active and
                  task.instances.latest('due_date') == instance):
                new = instance.create_next()
                if new is not None:
                    new.save()

    def _get_updated_task_instances(self, task):
        """
        Return tuple (current, previous) of updated task instances
        for the given task.

        Postcondition: task has at least 1 instance:
            current instance (today <= due_date < today+frequency)

        """
        instances = task.instances.order_by('-due_date')[:2]
        # note len() fetches the objects, but we need them anyway
        num_instances = len(instances)
        if num_instances == 2:
            # we have a current and a previous
            current = instances[0]
            prev = instances[1]
        elif num_instances == 1:
            # new instance, only current created
            current = instances[0]
            prev = None
        else:
            logger.error('Missing task instance for task_id %d' % task.id)
            current = TaskInstance.objects.create(
                task=task,
                #random first assignee
                assignee=random.choice(task.participants.all()),
                due_date=task.first_due
            )
            current.save()
            prev = None

        return (current, prev)

    def get_house_task_list(self, house):
        """
        Return list of task data for each of the given house's active tasks.

        """

        tasks = []
        for task in house.tasks.all():
            if not task.is_active:
                continue
            current, prev = self._get_updated_task_instances(task)
            t = {
                'title': task.title,
                'description': task.description,

fullhouse/templates/base.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

<!doctype html>
<html lang="en">
<title>
  Full House - 
  {% block title %}
    Welcome
  {% endblock %}
</title>
<head>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>

  <!-- Google Analytics -->
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-36074829-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
  <link rel="stylesheet" href="{{ STATIC_PREFIX }}main.css" />

  <!-- bootstrap -->
  <script src="{{ STATIC_PREFIX }}bootstrap/js/bootstrap.min.js"></script>
  <link href="{{ STATIC_PREFIX }}bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen" />
  <!-- bootbox -->
  <script src="{{ STATIC_PREFIX }}bootbox.min.js"></script>
</head>
{% if time %}
<script>
  {% if error %}
    setTimeout(function() { $("#error").fadeOut(500) }, {{ time }} * 1000);
  {% endif %}
  {% if message %}
    setTimeout(function() { $("#message").fadeOut(500) }, {{ time }} * 1000);
  {% endif %}
</script>
{% endif %}

{% block css %} {% endblock %}

{% block header %}
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a id="header-logo" href="{% url welcome %}"> 
         <img src="{{ STATIC_PREFIX }}header-logo.png" alt="logo"/>
      </a>
      <ul class="navlinks">
        <li><a href="{% url welcome %}">Home</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url edit_user %}">User Settings</a></li>
        <li><a href="{% url edit_house %}">House Settings</a></li>
        <li><a href="{% url auth_logout %}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}
<div id="main">
  {% if error %}
    <div id="error" class="error">
      {{ error }}
    </div>
  {% endif %}
  {% if message %}
    <div id="message" class="message">
      {{ message }}
    </div>
  {% endif %}
  
  {% block content %}
  <div class="
  <div class="error">
    There was an error fetching the web page.
  </div>
  {% endblock %}
</div>
<div id="footer">
  {% block footer %}  
    <br>
    <ul class="navlinks">
      <li><a href = "{% url about_us %}"><i class="icon-asterisk"></i> About Us</a></li>
      <li><a href = "{% url faq %}"><i class="icon-question-sign"></i> FAQ</a></li>
      <li><a href = "{% url contact_us %}"><i class="icon-envelope"></i> Contact Us</a></li>
    </ul>

  {% endblock %}
</div>
</html>

fullhouse/templates/contact_us.html
{% extends "base.html" %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

{% block title %}
  Contact_Us
{% endblock %}

{% block content %}
  <div id="contact_us">
    <h1 class="reg-header">Contact Us</h1>
    <iframe src="https://docs.google.com/spreadsheet/embeddedform?formkey=dEhPVXlOb19Yd2RYNWVLZmFiRDVXY0E6MQ" height="500px" width="100%" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
   </div>
{% endblock %}


<iframe src="https://docs.google.com/spreadsheet/embeddedform?formkey=dEhPVXlOb19Yd2RYNWVLZmFiRDVXY0E6MQ" width="760" height="681" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

fullhouse/templates/create_announcement.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% get_static_prefix as STATIC_PREFIX %}

{% block title %}
  Create Announcement
{% endblock %}

{% block content %}
  <div id="createannouncement">
    <h2>Create New Announcement</h2>
    <form name="create-announcement" action="." method="POST">
      {% csrf_token %}

      <div class = "fieldWrapper">
        {{ form.text.errors }}
        <label for="id_text">Announcement: </label>
        {{ form.text }}
      </div>

      <div class = "fieldWrapper">
        {{ form.expiration.errors }}
        <label for="id_expiration">Expiration (mm-dd-yyyy): </label>
        {{ form.expiration }}
      </div>

      <input type="submit" class="btn" value="{% trans 'Create Announcement' %}" />
    </form>
  </div>
{% endblock %}

fullhouse/templates/create_task.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% get_static_prefix as STATIC_PREFIX %}

{% block title %}
  Create Task
{% endblock %}

{% block content %}
  <div id="create-task">
    <h1>Create New Task</h1>
    <form name="create-task" action="." method="POST">
      {% csrf_token %}

      {{ form.as_p }}

      {% comment %}
      {{ form.non_field_errors }}

      <div class = "fieldWrapper">
        {{ form.title.errors }}
        <label form="title">Title: </label>
        {{ form.title }}
      </div>

      <div class = "fieldWrapper">
        {{ form.description.errors }}
        <label form="description">Description: </label>
        {{ form.description }}
      </div>

      <div class = "fieldWrapper">
        {{ form.participants.errors }}
        <label form="assigned">Participants (ctrl click to select multiple): </label>
        {{ form.participants }}
      </div>

     <div class = "fieldWrapper">
        {{ form.frequency.errors }}
        <label form="frequency">Frequency: </label>
        {{ form.frequency }}
      </div>

     <div class = "fieldWrapper">
        {{ form.first_due.errors }}
        <label form="first_due">First Due (MM-DD-YYYY): </label>
        {{ form.first_due }}
      </div>
      {% endcomment %}

      <div id="create-task-submit">
        <input type="submit" class="btn" value="{% trans 'Create Task' %}" />
      </div>
    </form>
  </div>
{% endblock %}

fullhouse/templates/edit_task.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% get_static_prefix as STATIC_PREFIX %}

{% block title %}
  Edit Task
{% endblock %}

{% block content %}
  <div id="createannouncement">
    <h2>Edit Task</h2>
    <form id="edit-task-form" action="." method="POST">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <input type="hidden" name="id" value="{{ id }}" />

      {{ form.as_p }}
      {% comment %}
      <div class = "fieldWrapper">
        {{ form.title.errors }}
        <label form="title">Title: </label>
        {{ form.title }}
      </div>

      <div class = "fieldWrapper">
        {{ form.description.errors }}
        <label form="description">Description: </label>
        {{ form.description }}
      </div>

      <div class = "fieldWrapper">
        {{ form.participants.errors }}
        <label form="assigned">Participants: </label>
        {{ form.participants }}
      </div>

     <div class = "fieldWrapper">
        {{ form.frequency.errors }}
        <label form="frequency">Frequency: </label>
        {{ form.frequency }}
      </div>

     <div class = "fieldWrapper">
        {{ form.first_due.errors }}
        <label form="first_due">First Due (MM-DD-YYYY): </label>
        {{ form.first_due }}
     </div>
     {% endcomment %}

      <input type="submit" class="btn" name="save" value="{% trans 'Save Changes' %}" />
      <a class="btn" href="#" id="delete-task-btn">Discontinue</a>
      <script>
        $('#delete-task-btn').click(function() {
          bootbox.dialog("{{ discontinue_task_message }}", [
            {
              'label': 'Discontinue',
              'class': 'btn-danger',
              'callback': function() {
                var delete_input = $("<input type='hidden' name='discontinue' />");
                $('#edit-task-form').append(delete_input).submit();
              }
            },
            {
              'label': 'Cancel',
              'class': 'btn-primary'
            }
          ]);
          return false;
        });
      </script>
    </form>
  </div>
{% endblock %}

fullhouse/templates/faq.html
{% extends "base.html" %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

{% block title %}
  FAQ
{% endblock %}

{% block content %}
  <div id="faq">
    <h1 class="reg-header">Frequently Asked Questions</h1>
    <h3 class="reg-header">What is Full House?</h3>
    <p class="reg-header"> Full House is your digital kitchen whiteboard.  It is here
    to help households manage common tasks-- taking out the trash, cleaning up the
    kitchen, and more.  Full House is here to make commnication between housemates 
    easy and convenient.
    </p>
    
    <h3 class="reg-header">How does it work?</h3>
    <p class="reg-header">
    Step one, <a href = "{% url registration_register %}">register</a> for Full House and validate
    your email address. 
    <br>
    Step two, <a href = "{% url dashboard %}">create a house</a> if you haven't already.
    <br>
    Step three, <a href = "{% url dashboard_add_members %}">invite housemates</a> to your house.
    <br>
    Step four, begin communicating with your housemates!
    </p>
    
    <h3 class="reg-header">How much does it cost?</h3>
    <p class="reg-header">
    Nothing! It's absolutely free!
    </p>
    
    <h3 class="reg-header">What kind of things can I do with Full House?</h3>
    <p class="reg-header">
    You can make a house with your friends. You can post announcements to let
    all your housemates know what is going on. You can create tasks that will
    cycle through the participating housemates so you always know whose turn it
    is to empty the dishwasher and who did it last. 
    </p>
    
    <h3 class="reg-header">How delicious are pretzels?</h3>
    <p class="reg-header">
		Too delicious for words.
    </p>
    &nbsp;
    <p class="reg-header">Project Full House, Copyright 2012. All rights reserved.</p>
   </div>
{% endblock %}

fullhouse/templates/handler403.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% get_static_prefix as STATIC_PREFIX %}

{% block title %}
  Handler 403
{% endblock %}

{% block content %}
  <div id="handler403">
    <h3 class="reg-header">That is not allowed!</h3>
    <p class="reg-header">Oops! It looks like you do not have permission to do whatever you just
    tried to do.
    <br>
    Please return to the <a href="{% url dashboard %}">dashboard</a> and try again.
    <br>
    If you continue to see this message, please <a href="{% url contact_us %}">contact us</a> for support.
    </p>
  </div>
{% endblock %}

fullhouse/templates/house_settings.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

{% block title %}
  House Settings
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ STATIC_PREFIX }}add_members.css" />
{% endblock %}

{% block content %}
  <div id="house-settings">
    <div id="emptyform">
      {{ formset.empty_form.as_p }}
    </div>
    {% if error %}
      {{ error }}
    {% else %}
      <h1>House Settings</h1>
      <form id="house-settings-form" name="house-settings" action="." method="POST">
        {% csrf_token %}
        <div>
          <input type="submit" class="btn" name="save" value="{% trans 'Save House Settings' %}" />
        </div>
        <br>

        {{ form.as_p }}

        <a class="btn" href="#" id="leave-house-btn">Leave this House</a>
        <script>
          $('#leave-house-btn').click(function() {
            bootbox.dialog("{{ leave_message }}", [
              {
                'label': 'Leave House',
                'class': 'btn-danger',
                'callback': function() {
                  var leave_input = $("<input type='hidden' name='leave_house' />");
                  $('#house-settings-form').append(leave_input).submit();
                }
              },
              {
                'label': 'Cancel',
                'class': 'btn-primary'
              }
            ]);
            return false;
          });
        </script>

        <script src="{{ STATIC_PREFIX }}add_members.js" ></script>
        <div id="addmembers">
          <h1>Housemates</h1>
          Current members:
          <ul class="members current">
          {% for member in members %}
            <li>{{ member }}</li>
          {% endfor %}
          </ul>
          {% if invitees|length != 0 %}
            Invited members:
            <ul class="members invite">
          {% endif %}
          {% for invitee in invitees %}
            <li>{{ invitee }} (<a href=".?uninvite={{invitee}}">Cancel invitation</a>)</li>
          {% endfor %}
          {% if invitees|length != 0 %}
            </ul>
          {% endif %}

          {{ formset.management_form }}
          {{ formset.non_form_errors }}
          <div id="forms">
            {% for form in formset.forms %}
              {{ form.as_p }}
            {% endfor %}
          </div>
          <div>
            <input type="button" class="btn" id="add_email" value="Add Row" />
          </div>
        </div>
        <br>

        <input type="submit" class="btn" name="save" value="{% trans 'Save House Settings' %}" />
      </form>
    {% endif %}
  </div>
{% endblock %}

fullhouse/templates/house_setttings.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

{% block title %}
  House Settings
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ STATIC_PREFIX }}house_settings.css" />
{% endblock %}

{% block content %}
  <div id="house-settings">
    {% if error %}
      {{ error }}
    {% else %}
      <h1 class="settings-head">House Settings</h1>
      <form name="house-settings" action="." method="POST">
        {% csrf_token %}

        {{ form.non_field_errors }}
        <div class="fieldWrapper">
          {{ form.name.errors }}
          <label form="housename">House Name: </label>
          {{ form.name }}
        </div>

        <div class="fieldWrapper">
          {{ form.zip_code.errors }}
          <label form="zipcode">Zip Code: </label>
          {{ form.zip_code }}
        </div>
        <input type="submit" value="{% trans 'Update House Settings' %}" />
      </form>
    {% endif %}
  </div>
{% endblock %}